zamong/src/App.tsx, zamong/src/index.tsx, zamong/src/route/MainRouter.tsx, zamong/src/route/RootRouter.tsx, zamong/src/route/index.ts
=> ⚡️ :: (#8) react router

zamong/src/container/Login/LoginContainer.tsx, zamong/src/container/Login/index.ts, zamong/src/container/index.ts, zamong/src/route/MainRouter.tsx
=> 10 container implementation

zamong/public/index.html, zamong/src/components/Login/Login.tsx, zamong/src/components/Login/Style.ts, zamong/src/style/globalStyle.ts, zamong/src/style/index.ts
=> 4 Login page UI

zamong/src/components/Signup/1/Signup.tsx, zamong/src/components/Signup/1/Style.ts, zamong/src/components/Signup/2/Signup.tsx, zamong/src/components/Signup/2/Style.ts, zamong/src/components/Signup/3/Signup.tsx, zamong/src/components/Signup/3/Style.ts
=> 5 Signup page UI

zamong/src/common/auth/Style.ts, zamong/src/components/Login/Style.ts, zamong/src/container/Login/LoginContainer.tsx
=> 25 Implement LoginContainer, RegisterContainer

zamong/src/components/Diary/Calendar/Calandar.tsx, zamong/src/components/Diary/Calendar/Calendar.tsx, zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts
=> Calendar Implementation

zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts, zamong/src/components/Header/Filter/Filter.tsx, zamong/src/components/Header/Header.tsx
=> 36 solve merge conflict

zamong/src/components/Diary/DiaryList/styles.ts, zamong/src/style/globalStyle.ts
=> ⚡️ :: (#26) Dream UI refactor

zamong/src/common/auth/Style.ts
=> Login Container

zamong/src/common/auth/AuthBackground.tsx, zamong/src/components/Diary/Calendar/Calendar.tsx, zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts, zamong/src/components/Login/Login.tsx, zamong/src/components/Sell/Main/SellMain.tsx, zamong/src/components/Signup/1/Signup.tsx, zamong/src/components/Signup/2/Signup.tsx, zamong/src/components/Signup/3/Signup.tsx, zamong/src/interfaces/Diary/index.ts, zamong/src/interfaces/Sell/index.ts
=> 35 Refactor Diary 

zamong/src/components/Sell/Main/SellMain.tsx, zamong/src/components/Sell/SellingDream/SellingDream.tsx, zamong/src/components/Sell/SellingDream/styles.ts
=> Selling Dreams Post Component

zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx, zamong/src/components/Footer/Footer.tsx, zamong/src/components/Footer/styles.ts, zamong/src/components/MainPage/FollowList/FollowList.tsx
=> 62 Footer Restyle

zamong/src/components/DiaryWrite/DiaryWrite.tsx, zamong/src/container/DiaryWrite/index.tsx
=> 73 Change Dream Write Header Footer Structure  

zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx, zamong/src/components/SellWrite/SellWrite.tsx, zamong/src/components/SellWrite/component/InputPrice/InputPrice.tsx, zamong/src/components/SellWrite/component/InputPrice/styles.ts, zamong/src/components/SellWrite/styles.ts, zamong/src/container/SellWrite/index.tsx, zamong/src/container/index.ts, zamong/src/route/MainRouter.tsx
=> 72 Sell Dream Write UI

zamong/src/components/MainPage/FollowList/FollowList.tsx, zamong/src/components/SignUp/SignUpND/SignUp.tsx, zamong/src/components/SignUp/SignUpST/SignUp.tsx, zamong/src/components/SignUp/SingUpRD/SignUp.tsx
=> :bug: :: (#54) Rename file

zamong/src/utils/api/default/index.ts, zamong/src/utils/axios/index.ts
=> 66 Set Api Default

zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/styles.ts
=> 94 Dream Diary Style

zamong/src/components/DiaryWrite/DiaryWrite.tsx
=> 86 Dream Diary Write Adding picture Implemented

zamong/.gitignore
=> 109 Add .env in .gitignore

zamong/src/components/Common/auth/styles.ts
=> 118 AuthBackground Style

zamong/src/components/Profile/style.ts
=> 146 Profile Page  Style

zamong/src/components/MainPage/MainPage.tsx, zamong/src/components/SignUp/SignUpND/styles.ts, zamong/src/container/MainPage/index.tsx
=> 150 Take measures right away

zamong/src/components/Login/Login.tsx, zamong/src/constance/uri.ts, zamong/src/utils/api/Login/index.ts, zamong/src/utils/api/default/index.ts
=> 83 Login Api

zamong/src/models/dto/response/dreamDetailResponse.ts, zamong/src/utils/api/DreamDetail/index.ts
=> 161 Dream detail get api

zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/Accordion.tsx, zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Content/Content.tsx, zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Header/Header.tsx, zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/styles.ts, zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/DreamQuality.tsx, zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/ItemContent/ItemContent.tsx, zamong/src/components/DiaryWrite/component/Properties/Selecter/Selecter/Selecter.tsx
=> 172 Change Diary Wirte Inner Component  style or function

zamong/src/components/DiaryWrite/component/ElapsedTime/ElapsedTime.tsx
=> 174 Fix Save Time 

zamong/src/components/Diary/Calendar/Calendar.tsx, zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts, zamong/src/components/Diary/DiaryTitle/DiaryTitle.tsx, zamong/src/components/Diary/DiaryTitle/styles.ts, zamong/src/utils/api/auth.ts, zamong/src/utils/api/calendar/index.ts, zamong/src/utils/api/default/index.ts
=> 81 Dream Diary Api

zamong/src/components/MainPage/Slider/Slider.tsx, zamong/src/components/MainPage/Slider/styles.ts
=> 178 Implementation slider functional

.github/workflows/zamong.yml
github action으로 master에 push될 때마다 빌드된 파일을 S3에 올리도록 했습니다.
master에 push되면 http://www.zamong.app.s3-website.ap-northeast-2.amazonaws.com 에서도 반영이 됩니다. 이제 CloudFront 연동하고 도메인 연결하면 될 것 같습니다
Closes #191
=> 191 Deploy S3 Action

zamong/src/models/dto/request/myShareDreamRequest.ts, zamong/src/utils/api/Main/index.ts
=> 169 Main Page API

zamong/src/constance/uri.ts, zamong/src/models/dto/response/followerResponse.ts, zamong/src/utils/api/Main/index.ts
=> 195 additional main page api

zamong/src/components/Login/Login.tsx
=> Login Enter

zamong/src/utils/api/Login/index.ts, zamong/src/utils/api/refresh.ts
=> 164 Fix expireAt type

zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
=> 205 Fix My recent dream diary list size bug

zamong/src/utils/api/Login/index.ts, zamong/src/utils/api/refresh.ts
=> 208 Fix Refresh Function

zamong/src/components/Header/LoginComponent/LoginComponent.tsx, zamong/src/components/Header/LoginComponent/styles.ts
=> 168 Implementation Functional Header

zamong/src/models/dto/response/sellDreamDetailResponse.tsx, zamong/src/utils/api/Sell/Main/index.ts
=> 218 get Sell Dream Detail API

zamong/src/components/DiaryWrite/DiaryWrite.tsx, zamong/src/constance/uri.ts, zamong/src/utils/api/DiaryWrite/index.ts, zamong/src/utils/api/DreamPosting/index.ts
=> 226 Change posting image uri

zamong/src/utils/api/Login/index.ts, zamong/src/utils/api/SignUp/index.ts, zamong/src/utils/api/refresh.ts
=> 221 Change instance to request

zamong/src/components/SellWrite/SellWrite.tsx, zamong/src/utils/api/SellWrite/index.ts
=> 228 sell dream put API

zamong/src/utils/api/Main/index.ts
=> 211 Main Page Share Dream API

zamong/src/components/DiaryWrite/DiaryWrite.tsx, zamong/src/components/DiaryWrite/component/styles.ts, zamong/src/components/SellWrite/SellWrite.tsx, zamong/src/components/SellWrite/component/InputPrice/Content/Content.tsx, zamong/src/components/SellWrite/component/InputPrice/InputPrice.tsx, zamong/src/container/SellWrite/index.tsx, zamong/src/utils/api/DiaryWrite/index.ts, zamong/src/utils/api/SellWrite/index.ts
=> 214 Write Sell Dream Functional implementation

zamong/src/components/Header/LoginComponent/LoginComponent.tsx, zamong/src/components/Header/LoginComponent/styles.ts, zamong/src/components/Header/styles.ts
=> 223 Reactive header implementation.

zamong/src/components/Diary/Calendar/Calendar.tsx, zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts, zamong/src/utils/api/Diary/MyDreams/index.ts
=> 225 My Dream Style Changes

zamong/src/components/DiaryDetail/Comment/Comment.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/Recommend/Recommend.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/ReplyComment/ReplyComment.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/ReplyComment/styles.ts, zamong/src/constance/uri.ts, zamong/src/utils/api/DreamDetail/index.ts
=> 154 Post Normal Comment

zamong/src/components/DiaryDetail/Comment/CommentBox/Recommend/Recommend.tsx
=> 242 Fix Recommend component type error 

zamong/src/components/Header/LoginComponent/LoginComponent.tsx
=> 238 Delete Dream Buy Nav

zamong/src/components/MainPage/styles.ts
=> 160 Main page size bug

zamong/src/components/Header/LoginComponent/LoginComponent.tsx, zamong/src/components/Profile/Account/AccountContent.tsx, zamong/src/components/Profile/Account/style.ts, zamong/src/components/Profile/Follow/FollowContent.tsx, zamong/src/components/Profile/Follow/style.ts, zamong/src/components/Profile/Follower/FollowerContent.tsx, zamong/src/components/Profile/Follower/style.ts, zamong/src/components/Profile/ProfilePage.tsx, zamong/src/components/Profile/style.ts, zamong/src/route/MainRouter.tsx, zamong/src/utils/api/Profile/index.ts
=> 186 Profile Under(2) api

zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts, zamong/src/utils/api/Diary/MyDreams/index.ts
=> 237 Dream Diary Api Changes

zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx, zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx, zamong/src/components/MainPage/Slider/Slider.tsx, zamong/src/components/MainPage/Slider/styles.ts
=> 250 Slider Arrow disable

zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx, zamong/src/models/dto/request/myDiaryRequest.ts, zamong/src/utils/api/Main/index.ts
=> 256 Fix get My diary

zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/Accordion.tsx, zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/styles.ts
=> 254 Accordion Menu header click

zamong/src/components/DiaryWrite/component/Picker/PickerColunm/PickerColumn.tsx, zamong/src/components/DiaryWrite/component/Picker/PickerColunm/styles.ts
=> 253 Picker scroll reverse

zamong/src/components/Diary/Calendar/Calendar.tsx, zamong/src/components/Sell/Main/SellMain.tsx, zamong/src/components/Sell/SellingDream/SellingDream.tsx, zamong/src/utils/api/Diary/Calendar/index.ts, zamong/src/utils/api/Sell/Main/index.ts
=> 236 Joy Api Instance

zamong/src/components/Header/LoginComponent/LoginComponent.tsx, zamong/src/components/Header/LoginSkeleton/LoginSkeleton.tsx, zamong/src/components/Header/LoginSkeleton/styles.ts
=> 262 on router change header blink 

zamong/src/components/Header/LoginComponent/LoginComponent.tsx, zamong/src/components/MainPage/MainPage.tsx, zamong/src/components/Profile/Account/AccountContent.tsx, zamong/src/components/Profile/Follow/FollowContent.tsx, zamong/src/components/Profile/Follower/FollowerContent.tsx, zamong/src/components/Profile/ProfilePage.tsx, zamong/src/utils/api/DiaryWrite/index.ts, zamong/src/utils/api/DreamDetail/index.ts, zamong/src/utils/api/Main/index.ts, zamong/src/utils/api/Profile/index.ts, zamong/src/utils/api/default/index.ts
=> 271 change request to axios instance

zamong/src/components/DiaryWrite/DiaryWrite.tsx, zamong/src/components/Header/LoginComponent/LoginComponent.tsx, zamong/src/components/MainPage/MainPage.tsx
=> 267 on login then Diary Write 

zamong/src/components/Header/Header.tsx, zamong/src/components/MainPage/MainPage.tsx, zamong/src/utils/api/refresh.ts
=> 273 change axios instance login 

zamong/src/components/Header/Filter/Filter.tsx
=> 239 Filter deactive when click Another place

zamong/src/components/Header/Filter/styles.ts
=> 216 add Shadow in filter

zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx, zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx, zamong/src/components/CardDream/index.ts, zamong/src/components/Sell/SellingDream/SellingDream.tsx, zamong/src/components/Sell/SellingDream/styles.ts
=> 263 Link to Detail

zamong/src/components/Sell/Main/SellMain.tsx
=> 280 Dream Sell Smooth Scroll Change

zamong/src/utils/api/Main/index.ts
=> 284 Change Follow and etc API Call

zamong/src/components/SignUp/SignUpND/styles.ts, zamong/src/components/SignUp/SignUpST/styles.ts, zamong/src/components/SignUp/SingUpRD/styles.ts
=> 294 SignUp Cursor pointer

zamong/public/index.html, zamong/src/components/Header/Header.tsx
=> 297 Router Change ScrollTop

zamong/src/route/MainRouter.tsx
=> 251 Link the post

zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/Accordion.tsx
=> 290 fix accordion header click bug

zamong/src/components/CardDream/index.ts, zamong/src/components/Dream/styles.ts, zamong/src/components/Header/styles.ts, zamong/src/components/MainPage/MainPage.tsx
=> 305 Optimization css

zamong/src/components/Diary/Calendar/Calendar.tsx
=> 325 Fix Calendar

zamong/src/components/CardDream/index.ts, zamong/src/constance/uri.ts, zamong/src/utils/api/DreamInterpretationMain/index.ts
=> 314 interpretation of a dream main page API

zamong/src/constance/uri.ts
=> 328 fix follow uri none 

zamong/src/components/CardDream/FollowDreamDiary/styles.ts, zamong/src/components/CardDream/MyDreamDiary/styles.ts, zamong/src/components/CardDream/index.ts
=> 330 Fix Diary Card style

zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx, zamong/src/components/Profile/AnotherUser/styles.ts, zamong/src/components/Profile/Follow/FollowContent.tsx, zamong/src/components/Profile/Follower/FollowerContent.tsx, zamong/src/components/Profile/ProfilePage.tsx, zamong/src/container/Profile/AnotherUser/index.tsx, zamong/src/container/index.ts, zamong/src/models/dto/response/profileResponse.ts, zamong/src/route/MainRouter.tsx, zamong/src/utils/api/Profile/index.ts
=> 187 Another User's Profile api

zamong/src/components/Dream/Dream.tsx, zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx, zamong/src/components/Dream/styles.ts
=> 194 Add link in Main Page

zamong/src/components/Dream/styles.ts
=> 233 Dream List Name Position fix

zamong/src/models/dto/response/diaryWriteResponse.ts, zamong/src/models/dto/response/dreamDetailResponse.ts, zamong/src/models/dto/response/dreamListResponse.ts, zamong/src/models/dto/response/followingsResponse.ts, zamong/src/models/dto/response/profileResponse.ts, zamong/src/models/dto/response/sellDreamDetailResponse.ts, zamong/src/models/dto/response/shareDreamResponse.ts
=> 344 change response use default response

zamong/src/components/Header/Filter/FilterContent/FilterContent.tsx
=> 347 fix filter tag click bug

zamong/src/components/DiaryWrite/component/Picker/Modal/Modal.tsx, zamong/src/components/DiaryWrite/component/Picker/PickerColunm/PickerColumn.tsx, zamong/src/components/Header/LoginComponent/LoginComponent.tsx
=> 261 when another place click, Picker Modal become close 

zamong/src/components/DiaryWrite/DiaryWrite.tsx, zamong/src/components/DiaryWrite/component/ElapsedTime/ElapsedTime.tsx, zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Content/Content.tsx, zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Header/Header.tsx, zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/ItemContent/ItemContent.tsx, zamong/src/components/Header/LoginComponent/LoginComponent.tsx
=> 317 diary write last save time bug & type is empty but can post bug 

zamong/src/components/SignUp/SignUp.tsx
=> 341 Sign Up Alert

zamong/src/components/DiaryWrite/DiaryWrite.tsx
=> 316 fix Temporary save 

zamong/src/components/Profile/Account/AccountContent.tsx, zamong/src/components/Profile/Account/style.ts
=> 334 Profile Button style 수정

zamong/src/components/Profile/Account/style.ts
=> 355 font로 체인지

zamong/src/components/Footer/Footer.tsx, zamong/src/components/Footer/styles.ts
=> 360 add Footer Margin

zamong/src/components/Profile/Follow/FollowContent.tsx, zamong/src/components/Profile/Follow/style.ts, zamong/src/components/Profile/Follower/FollowerContent.tsx, zamong/src/components/Profile/Follower/style.ts
=> 377 When don't have follow or followers

zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts, zamong/src/utils/api/DreamDetail/index.ts
=> 366 Comment Profile

zamong/src/models/dto/request/postInterpretationRequest.ts, zamong/src/models/dto/response/interpretationDetailResponse.ts, zamong/src/utils/api/InterpretationWrite/index.ts
=> 371 interpretation write API

zamong/src/components/Profile/Account/AccountContent.tsx, zamong/src/utils/api/Profile/index.ts
=> 373 Account Secession API

zamong/src/components/InterpretationWrite/InterpretationWrite.tsx, zamong/src/container/InterpretationWrite/index.tsx, zamong/src/models/dto/request/postInterpretationRequest.ts, zamong/src/models/dto/response/interpretationDetailResponse.ts, zamong/src/utils/api/InterpretationWrite/index.ts
=> 372 realize interpretation write fuction

zamong/src/components/Header/Header.tsx
=> 392 header serach function

zamong/src/components/Chat/Chat.tsx, zamong/src/components/Chat/styles.ts, zamong/src/interface/Chat/index.ts, zamong/src/utils/api/Chat/index.ts
=> 282 Chat Implementation

zamong/src/components/Common/auth/AuthBackground.tsx, zamong/src/components/Common/auth/styles.ts
> 일단은 타이핑 애니메이션 추가 했는데 마음에 안 들면 그 줄 정렬로 아래서 위로 함
=> 393 Auth Animation 

zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx, zamong/src/models/dto/response/InterpretationListResponse.ts
=> 400 add lucy on interpretation list response

zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx, zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
=> 399 change link on card and list

zamong/src/components/DiaryDetail/Posting/Posting.tsx, zamong/src/components/InterpretationDetail/Posting/Posting.tsx, zamong/src/components/SellDetail/Posting/Posting.tsx
=> 408 fix detail not enterd

zamong/src/components/InterpretationDetail/Comment/CommentBox/AdoptComment/styles.ts, zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts
=> 407 Interpretation Answerer 

zamong/src/style/globalStyle.ts
=> 401 auto fill background color change

zamong/src/components/InterpretationDetail/Comment/CommentBox/AdoptComment/AdoptComment.tsx, zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
=> 406 Interpretation Render

zamong/src/components/DiaryWrite/component/Properties/Selecter/Selecter/Selecter.tsx, zamong/src/components/InterpretationWrite/InterpretationWrite.tsx, zamong/src/components/InterpretationWrite/components/LucyInput/Content/Content.tsx
=> 403 interpretation write now lucy count 

zamong/src/components/DiaryWrite/DiaryWrite.tsx
=> 375 delete save when on post 

zamong/src/components/MainPage/MainPage.tsx
=> 419 fix main page nav 

zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts
=> 420 Diary Page Refactor

zamong/src/components/DreamInterpretationMain/DreamInterpretationList/DreamInterpretationList.tsx, zamong/src/components/MainPage/DreamList/DreamList.tsx
=> 240 when more page add

zamong/src/components/SellDetail/Chat/Chat.tsx, zamong/src/components/SellDetail/Chat/styles.ts
=> 430 fix gap on chat request

zamong/src/components/PageNation/PageNation.tsx
=> 427 fix page nation component

zamong/src/components/MainPage/MainPage.tsx
=> 439 add sign up link on non login hello message

zamong/src/components/DreamInterpretationMain/DreamInterpretationList/DreamInterpretationList.tsx, zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx, zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx, zamong/src/components/MainPage/DreamList/DreamList.tsx, zamong/src/components/MainPage/FollowList/FollowList.tsx, zamong/src/components/MainPage/FollowList/styles.ts, zamong/src/constance/defaultImageList.ts
=> 437 apply skeleton

zamong/src/components/ChangePassword/ChangePassword.tsx, zamong/src/components/FindPassword/FindPassword.tsx
=> 442 Folder Name Error

zamong/src/components/SellDetail/Chat/styles.ts
=> 444 Sell Dream Style

zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/DiaryDetail/Head/Head.tsx, zamong/src/components/DiaryDetail/Head/styles.ts, zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/InterpretationDetail/Head/Head.tsx, zamong/src/components/InterpretationDetail/Head/styles.ts, zamong/src/components/SellDetail/Chat/Chat.tsx, zamong/src/components/SellDetail/Chat/styles.ts, zamong/src/components/SellDetail/Head/Head.tsx, zamong/src/components/SellDetail/Head/styles.ts
=> 446 Profile Link

zamong/src/components/DiaryDetail/Comment/Comment.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/DiaryDetail/DiaryDetail.tsx, zamong/src/components/DiaryDetail/Head/Head.tsx, zamong/src/components/InterpretationDetail/Comment/Comment.tsx, zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/InterpretationDetail/Head/Head.tsx
=> 451 Modify comment

zamong/src/components/MainPage/FollowList/FollowList.tsx, zamong/src/components/MainPage/FollowList/styles.ts
=> 461 following list more action

zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx, zamong/src/components/Profile/Follow/FollowContent.tsx, zamong/src/components/Profile/Follower/FollowerContent.tsx, zamong/src/components/Profile/ProfilePage.tsx
=> 458 profile query string

zamong/src/components/Login/Login.tsx, zamong/src/components/Login/styles.ts
=> 457 sign up link in login page

zamong/src/components/Diary/Calendar/styles.ts, zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/DiaryDetail/Posting/Posting.tsx, zamong/src/components/Dream/Dream.tsx, zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx, zamong/src/components/DreamInterpretationMain/DefaultDreamInterpretation/DefaultDreamInterpretation.tsx, zamong/src/components/InterpretationDetail/Posting/Posting.tsx, zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx, zamong/src/components/MainPage/DreamList/DreamList.tsx, zamong/src/components/MainPage/FollowList/FollowList.tsx, zamong/src/components/MainPage/MainPage.tsx, zamong/src/components/Search/SearchPage.tsx, zamong/src/components/Sell/Main/SellMain.tsx, zamong/src/components/SellDetail/Posting/Posting.tsx
=> 463 fix map key error

zamong/src/components/Diary/DiaryList/DiaryList.tsx, zamong/src/components/Diary/DiaryList/styles.ts
=> 466 change diary style

zamong/src/components/DiaryDetail/Head/Head.tsx, zamong/src/components/InterpretationDetail/Head/Head.tsx, zamong/src/components/SellDetail/Head/Head.tsx, zamong/src/container/index.ts
=> ⚡️ :: (#451) Detail Head

zamong/src/components/DiaryDetail/Head/Head.tsx, zamong/src/components/InterpretationDetail/Head/Head.tsx, zamong/src/components/SellDetail/Chat/Chat.tsx, zamong/src/components/SellDetail/Head/Head.tsx
=> 477 After Delete Move To Previous Page

zamong/src/components/DiaryDetail/Comment/Comment.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts, zamong/src/components/DiaryDetail/Comment/styles.ts, zamong/src/components/InterpretationDetail/Comment/Comment.tsx, zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts, zamong/src/components/InterpretationDetail/Comment/styles.ts, zamong/src/utils/api/DreamDetail/index.ts
=> 474 Anonymous comment

zamong/src/components/DiaryDetail/Posting/Posting.tsx, zamong/src/components/DiaryDetail/Posting/styles.ts, zamong/src/constance/defaultImageList.ts
=> 484 default image action

zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx, zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
=> 486 can enter profile even thought Anonymous comment

.github/workflows/zamong.yml
=> 490 zamong.org auto distribution settings

zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts, zamong/src/components/DiaryDetail/Head/styles.ts, zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts, zamong/src/components/InterpretationDetail/Head/styles.ts, zamong/src/components/SellDetail/Head/styles.ts
=> 505 Comment Profile
